### ISSUE TITLE
[Missing Textures] Pam's HarvestCraft 1.9.4-1.10.2h.jar - Forge 215 - 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MatrexsVigil/harvestcraft#206] opened 2017-01-15 01:17 UTC
![2017-01-14_19 14 42](https://cloud.githubusercontent.com/assets/10351221/21959465/06b6cf40-da8e-11e6-807a-09634f251a73.png)
![2017-01-14_19 14 43](https://cloud.githubusercontent.com/assets/10351221/21959467/06b7b3f6-da8e-11e6-8a5b-7ea5536c7627.png)
![2017-01-14_19 14 44](https://cloud.githubusercontent.com/assets/10351221/21959463/06b685ee-da8e-11e6-957f-42f32fe2271f.png)
![2017-01-14_19 14 45](https://cloud.githubusercontent.com/assets/10351221/21959466/06b6e4a8-da8e-11e6-87f7-4f33b0dfc3e1.png)
![2017-01-14_19 14 46](https://cloud.githubusercontent.com/assets/10351221/21959464/06b6d8c8-da8e-11e6-85bc-85eeffe5c19b.png)
![2017-01-14_19 14 47](https://cloud.githubusercontent.com/assets/10351221/21959468/06b87c32-da8e-11e6-9258-6faf78ffad4a.png)
![2017-01-14_19 14 48](https://cloud.githubusercontent.com/assets/10351221/21959471/06c2d65a-da8e-11e6-9c89-3152d6617ee1.png)
![2017-01-14_19 14 49](https://cloud.githubusercontent.com/assets/10351221/21959469/06c1ae60-da8e-11e6-82ad-2aa85fac6797.png)
![2017-01-14_19 14 51](https://cloud.githubusercontent.com/assets/10351221/21959470/06c1b464-da8e-11e6-8538-86df6930dc92.png)
![2017-01-14_19 14 52](https://cloud.githubusercontent.com/assets/10351221/21959472/06c2ed5c-da8e-11e6-9ee3-e99ee1beff0f.png)

**Comment by warlordjones** [comment] 2017-01-19 17:00
Duplicate of #190

**Closed** 2017-01-19 19:56 UTC

**Comment by P3rf3ctXZer0** [comment] 2017-01-20 00:17
@warlordjones needs 1.10.2 release please!

**Comment by warlordjones** [comment] 2017-01-21 11:34
Afraid not. Even maintenance patches are only going be released on the latest version at this time.

**Comment by P3rf3ctXZer0** [comment] 2017-01-21 19:21
Well then this mod no longer holds my interest. I cannot update until all the mods I use also update.

**Comment by P3rf3ctXZer0** [comment] 2017-01-21 19:29
I don't normally get annoyed with that but please keep this mode properly updated till this mod is up and working https://github.com/SlimeKnights/TinkersConstruct/issues/2724

**Comment by warlordjones** [comment] 2017-01-21 21:49
Pam is currently quite sick and I am doing my best to take the load off her so she can rest. Please don't stress her out further.

Additionally, a few missing textures is not exactly equivalent to a game-breaking crash preventing you from playing with or enjoying the mod.
