### ISSUE TITLE
Can't place gardens on Biomes O'Plenty grass

### ISSUE THREAD

**Issue by Syndaryl** [MatrexsVigil/harvestcraft#195] opened 2016-11-19 21:50 UTC
I think they also won't spawn on or spread naturally to these grasses either. These are things like the Loamy Grass, Sandy Grass, and so forth. This means there's entire biomes that can't have Pam's resources.

**Comment by warlordjones** [comment] 2017-01-19 20:17
Dupe of #149

**Closed by warlordjones** 2017-01-19 20:17 UTC
