### ISSUE TITLE
Bug: Hopper loading and unloading of presser

### ISSUE THREAD

**Issue by jamesfhj** [MatrexsVigil/harvestcraft#175] opened 2016-10-15 00:16 UTC
Hoppers loading items into the top of the presser loads all three slots instead of just the top slot. Hoppers unloading the presser from the bottom pulls from all three slots instead of just the bottom two.

**Comment by remeisigma** [comment] 2016-11-07 02:30
I think this is related to/a duplicate of [https://github.com/MatrexsVigil/harvestcraft/issues/161](this) issue. I've actually got NO idea how to link the two issues in GitHub, though, so someone who does know can handle that.

**Comment by Jamdog** [comment] 2016-11-28 09:56
Issue originally referenced here: #159

**Closed** 2017-01-19 20:13 UTC
Labels: duplicate
