### ISSUE TITLE
Custom fish are not under the oredic listAllfishraw

### ISSUE THREAD

**Issue by Roxforbraynz** [MatrexsVigil/harvestcraft#147] opened 2016-08-05 21:28 UTC
This makes them unable to be used in several recipes requiring raw fish, such as sushi, fish sticks, fish sandwich and especially fish trap bait. Given the rarity of vanilla fish due to all the custom fish, this tends to be an issue.

**Comment by bennyman123abc** [comment] 2016-09-03 15:12
If it is fish from another mod, that issue is not caused by this mod and the owner of the GitHub Repo should close this issue.

**Comment by Roxforbraynz** [comment] 2016-09-03 19:04
@bennyman123abc The only custom fish at the time were from Harvestcraft and I listed recipes from Harvestcraft itself that only use vanilla fish and excludes it's own custom fish due to the missing oredic. The issue persists.

**Comment by bennyman123abc** [comment] 2016-09-09 00:02
@Roxforbraynz I'm sorry. Didn't realize that HarvestCraft had it's own fish until I just went through the code. If the author ever comes back to GitHub, I will add everything to the oredic as they should be and make a pull request.

**Comment by Syndaryl** [comment] 2016-09-11 20:54
@bennyman123abc MatrexsVigil is active and has not "gone away" from GitHub. She's taking some time to update her other mods to 1.10.2 as they haven't been bumped up yet, but there's no reason why you couldn't go ahead with a pull request while she does that.

**Comment by bennyman123abc** [comment] 2016-09-18 01:40
@Syndaryl Sorry. I thought that those changes have already been pushed to the GitHub and she was taking time off. I will go ahead and make the changes required then and I will make a pull request. Thanks for the tip

**Comment by bennyman123abc** [comment] 2016-09-29 01:39
Looked into it and all of the fish are already in the oredic listAllfishraw

**Closed** 2017-01-19 19:50 UTC
Labels: invalid
