### ISSUE TITLE
Server Crash On Startup 1.9 

### ISSUE THREAD

**Issue by MrThomson** [MatrexsVigil/harvestcraft#94] opened 2016-05-09 15:00 UTC
The Mod Verison Pam's HarvestCraft 1.9a

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
  MalisisSwitchesPlugin (malisisswitches-1.9-2.0.0.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 5/9/16 11:01 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.item.ItemMonsterPlacer.func_185078_a(Lnet/minecraft/item/ItemStack;Ljava/lang/String;)V
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:587)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:93)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:119)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemMonsterPlacer.func_185078_a(Lnet/minecraft/item/ItemStack;Ljava/lang/String;)V
	at com.pam.harvestcraft.gui.MarketItems.registerItems(MarketItems.java:312)
	at com.pam.harvestcraft.HarvestCraft.preInit(HarvestCraft.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:561)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:584)
	... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Linux (amd64) version 2.6.32-573.7.1.el6.x86_64
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2330808728 bytes (2222 MB) / 3009413120 bytes (2870 MB) up to 3009413120 bytes (2870 MB)
	JVM Flags: 5 total; -Xms3000M -Xmx3000M -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:ParallelGCThreads=4
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.1.1889 71 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1889-universal.jar) 
	UCH	Forge{12.16.1.1889} [Minecraft Forge] (forge-1.9-12.16.1.1889-universal.jar) 
	UCH	Baubles{1.2.0.2} [Baubles] (Baubles-1.9-1.2.0.2.jar) 
	UCH	baublesstuff{2.0.7} [Baubles Stuff] (baublesstuff-2.0.7.jar) 
	UCH	bdlib{1.11.0.14} [BD Lib] (bdlib-1.11.0.14-mc1.9.jar) 
	UCH	BetterAchievements{0.2.5.19} [Better Achievements] (BetterAchievements-1.9-0.2.5.19.jar) 
	UCH	BBG{4.0.0} [BetterBedrockGen] (BetterBedrockGenerator-1.9.0-3.0.0.jar) 
	UCH	BiomesOPlenty{4.0.1.2006} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.1.2006-universal.jar) 
	UCH	JEI{3.3.3.197} [Just Enough Items] (jei_1.9-3.3.3.197.jar) 
	UCH	BloodMagic{1.9-2.0.0-35} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9-2.0.0-35.jar) 
	UCH	bookshelfapi{3.0.4} [Bookshelf] (Bookshelf-API-1.9-3.0.4.jar) 
	UCH	chancecubes{1.9-2.1.1.98} [Chance Cubes] (ChanceCubes-1.9-2.1.1.98.jar) 
	UCH	ChestTransporter{2.3.0} [Chest Transporter] (ChestTransporter-2.3.0-MC1.9.jar) 
	UCH	chisel{@VERSION@} [Chisel] (Chisel-MC1.9-0.0.4.13.jar) 
	UCH	mcmultipart{1.1.1} [MCMultiPart] (MCMultiPart-1.1.1-universal.jar) 
	UCH	chiselsandbits{9.15} [Chisels & Bits] (chiselsandbits-9.15.jar) 
	UCH	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-2.1-1.9-rc.jar) 
	UCH	cookingforblockheads{2.0.5} [Cooking for Blockheads] (CookingForBlockheads-mc1.9-2.0.5.jar) 
	UCH	craftablenametags{1.2} [Craftable Name Tags] (craftablenametags-1.2.jar) 
	UCH	craftingtweaks{4.0.10} [Crafting Tweaks] (craftingtweaks-mc1.9-4.0.10.jar) 
	UCH	MineTweaker3{3.0.7} [MineTweaker 3] (CraftTweaker-Customized-1.9-3.0.7.jar) 
	UCH	cyclopscore{0.5.8} [Cyclops Core] (CyclopsCore-1.9-0.5.8.jar) 
	UCH	EnderBags{1.0.1} [EnderBags] (EnderBags-1.9-1.0.1.jar) 
	UCH	evilcraft{0.9.9} [EvilCraft] (EvilCraft-1.9-0.9.9.jar) 
	UCH	excore{1.5.3} [EXCore] (Excore-1.5.3-1.9.jar) 
	UCH	extrathings{0.2.0} [Extra Things] (extraThings-0.2.0.jar) 
	UCH	ezstorage{1.0} [EZ Storage] (ezstorage-1.9-1.2.1.jar) 
	UCH	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar) 
	UCH	substratum{1.3.0.0} [Substratum] (Substratum-1.9-1.3.0.0.jar) 
	UCH	foundry{2.0.0.0-alpha2} [Foundry] (Foundry-1.9-2.0.0.0-alpha2.jar) 
	UCH	furnus{1.74} [Furnus] (Furnus-1.9-1.74.jar) 
	UCH	advgenerators{0.9.20.8} [Advanced Generators] (generators-0.9.20.8-mc1.9.jar) 
	UCH	graves{1.9-b10-universal} [Graves Mod] (graves-1.9-b10-universal.jar) 
	UCH	HardcoreQuesting{5.0.0alpha1} [Hardcore Questing Mode] (HQM-New Heights-5.0.0alpha1.jar) 
	UCH	IronChest{6.0.133.777} [Iron Chest] (ironchest-1.9-6.0.133.777.jar) 
	UCH	journeymap{1.9-5.2.0b1} [JourneyMap] (journeymap-1.9-5.2.0b1-unlimited.jar) 
	UCH	LunatriusCore{1.1.2.34} [LunatriusCore] (LunatriusCore-1.9-1.1.2.34-universal.jar) 
	UCH	malisiscore{1.9-3.0.6} [MalisisCore] (malisiscore-1.9-3.0.6.jar) 
	UCH	malisisblocks{1.9-3.0.1} [Malisis Blocks] (malisisblocks-1.9-3.0.1.jar) 
	UCH	malisisdoors{1.9-4.0.1} [MalisisDoors] (malisisdoors-1.9-4.0.1.jar) 
	UCH	malisisswitches{1.9-2.0.0} [Malisis Switches] (malisisswitches-1.9-2.0.0.jar) 
	UCH	mantle{1.9-0.10.0.jenkins132} [Mantle] (Mantle-1.9-0.10.0.jar) 
	UCH	RadixCore{1.9-2.1.0} [RadixCore] (RadixCore-1.9-2.1.0-universal.jar) 
	UCH	MCA{1.9-5.1.2} [Minecraft Comes Alive] (MCA-1.9-5.1.2-universal.jar) 
	UCH	testdummy{1.10} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.10.jar) 
	UCH	Morpheus{1.9-3.0.2} [Morpheus] (Morpheus-1.9-3.0.2.jar) 
	UCH	tconstruct{1.9-2.3.0.jenkins193} [Tinkers' Construct] (TConstruct-1.9-2.3.0.jar) 
	UCH	neotech{3.0.6} [NeoTech] (NeoTech-1.9-3.0.6.jar) 
	UCH	notenoughwands{1.3.2} [Not Enough Wands] (notenoughwands-1.9.0-1.3.2.jar) 
	UCE	harvestcraft{1.9a} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9a.jar) 
	UCH	progressiveautomation{1.6.42} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.42.jar) 
	UCH	Psi{beta-31} [Psi] (Psi-beta-31.jar) 
	UCH	quantumflux{2.0.6} [QuantumFlux] (quantumflux-1.9-2.0.6.jar) 
	UCH	randomthings{3.7} [Random Things] (RandomThings-MC1.9-3.7.jar) 
	UCH	reborncore{2.1.0.53} [RebornCore] (RebornCore-1.9-2.1.0.53-universal.jar) 
	UCH	xreliquary{1.9-1.3.1.338} [Reliquary] (Reliquary-1.9-1.3.1.338.jar) 
	UCH	rftools{4.46} [RFTools] (rftools-1.9.0-4.46.jar) 
	UCH	rftoolsdim{4.23beta37} [RFTools Dimensions] (rftoolsdim-1.9.0-4.23beta37.jar) 
	UCH	Roguelike{1.5.0} [Roguelike Dungeons] (RoguelikeDungeons-1.9-1.5.0.jar) 
	UCH	shetiphiancore{3.2.1} [ShetiPhian-Core] (shetiphiancore-1.9.0-3.2.1.jar) 
	UCH	simpleretrogen{2.2.3+4} [Simple Retrogen] (simpleretrogen-1.9-2.2.3+4.jar) 
	UCH	soulshardstow{1.9-2.3.9-25} [Soul Shards - The Old Ways] (SoulShards-TOW-1.9-2.3.9-25.jar) 
	UCH	techreborn{1.0.6.197} [TechReborn] (TechReborn-1.9-1.0.6.197-universal.jar) 
	UCH	Torcherino{@VERSION@} [Torcherino] (Torcherino-TehNut-1.9-2.2s.jar) 
	UCH	trashslot{3.0.4} [TrashSlot] (trashslot-mc1.9-3.0.4.jar) 
	UCH	VeinMiner{0.31.5_build.forgePost18010} [Vein Miner] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UCH	VeinMinerModSupport{0.31.5_build.forgePost18010} [Mod Support] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B2_1.9.jar) 
	UCH	wailafeatures{@MAJOR@.@MINOR@.@REVIS@} [WAILA Features] (WAILA-features-1.9-0.3.1.6.jar) 
	UCH	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.9-1.1.7.jar) 
	Loaded coremods (and transformers): 
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  lumien.randomthings.asm.ClassTransformer
Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  reborncore.asm.RebornClassTransformer
MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
MalisisSwitchesPlugin (malisisswitches-1.9-2.0.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* Baubles|API (1.1.1.0) from Baubles-1.9-1.2.0.2.jar
		* BetterAchievements|API (0.2.5.19) from BetterAchievements-1.9-0.2.5.19.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9-2.0.0-35.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
		* ChiselsAndBitsAPI (1.8.1) from chiselsandbits-9.15.jar
		* CoFHAPI (1.8.9R1.2.0B1) from Foundry-1.9-2.0.0.0-alpha2.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* compactstorage (v2.0.0a) from compactstorage-2.1-1.9-rc.jar
		* CraftingTweaks|API (4.1) from craftingtweaks-mc1.9-4.0.10.jar
		* foundry.api (2.0.0.0) from Foundry-1.9-2.0.0.0-alpha2.jar
		* IC2API (1.0) from RebornCore-1.9-2.1.0.53-universal.jar
		* jeresources|API (0.4.5.25) from JustEnoughResources-1.9-0.4.5.25.jar
		* journeymap|client-api (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-display (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-event (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-model (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-util (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.9-3.3.3.197.jar
		* McJtyLib (1.9.0-1.8.3) from mcjtylib-1.9.0-1.8.3.jar
		* PsiAPI (2) from Psi-beta-31.jar
		* reborncoreAPI (2.1.0.53) from RebornCore-1.9-2.1.0.53-universal.jar
		* SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.9-2.3.9-25.jar
		* techrebornAPI (1.0.6.197) from TechReborn-1.9-1.0.6.197-universal.jar
		* VeinMinerApi (0.1) from VeinMiner-1.9_0.31.5.forgePost18010.jar
		* WailaAPI (1.3) from Waila-1.7.0-B2_1.9.jar
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by lebertran** [comment] 2016-05-13 11:08
Duplicate of #88. Fixed in next release (see fork).

**Closed** 2016-05-15 20:26 UTC
